EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    only:
      - Style/StringLiterals
      - Style/FrozenStringLiteralComment
      - Layout/TrailingWhitespace